version: "3.4"
services:
  requestrr:
    image: darkalfx/requestrr
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - /path to config:/root/config
    - /path to logs:/root/logs
    restart: unless-stopped